### NumPy Review

---

In [ ]:
import numpy as np

**1D Array with NumPy**

In [ ]:
arr_1 = np.arange(7) # arr_1 = np.array([0, 1, 2, 3, 4, 5, 6])
arr_1 = arr_1.astype(np.float32) # change type of array element
print(arr_1)
print("Rank  of array: ", arr_1.ndim)
print("Shape of array: ", arr_1.shape)

[0. 1. 2. 3. 4. 5. 6.]
Rank  of array:  1
Shape of array:  (7,)


In [ ]:
print("array[0]   array[1] array[-1] = ", arr_1[0], arr_1[1], arr_1[-1]) # Element
print("array[2:5] array[4:-1]      = ", arr_1[2:5], arr_1[4:-1])         # Slicing
print("array[:2]  array[3:]         = ", arr_1[:2], arr_1[3:])           # Slicing  

array[0]   array[1] array[-1] =  0.0 1.0 6.0
array[2:5] array[4:-1]      =  [2. 3. 4.] [4. 5.]
array[:2]  array[3:]         =  [0. 1.] [3. 4. 5. 6.]


**2D Array with Numpy**

In [ ]:
arr_2 = np.arange(1,13).reshape(4,3) # arr_2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
arr_2 = arr_2.astype(np.float32) # chane type of array element
print(arr_2)
print("Rank  of array: ", arr_2.ndim)
print("Shape of array: ", arr_2.shape)
print("array[0][0] array[2][1] array[3][2] = ", arr_2[0][0], arr_2[2][1], arr_2[3][2]) # Element
print("array[0], array[:,0], array[0,:]    = ", arr_2[0], arr_2[:,0], arr_2[0,:])      # Slicing
print("array[1:3,1:2] = \n", arr_2[2:4,1:3]) # Slicing

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Rank  of array:  2
Shape of array:  (4, 3)
array[0][0] array[2][1] array[3][2] =  1.0 8.0 12.0
array[0], array[:,0], array[0,:]    =  [1. 2. 3.] [ 1.  4.  7. 10.] [1. 2. 3.]
array[1:3,1:2] = 
 [[ 8.  9.]
 [11. 12.]]


# CH1. Basic PyTorch

2022 2학기 IT집중교육에서는 딥러닝 실습을 위해서 PyTorch 딥러닝 프레임워크를 이용합니다. PyTorch를 이용하여 신경망을 학습하기 위해서 텐서조작, 간단한 신경망 구성 부터 시작하여 CNN, Object Detection, Segmentation, Vision Transformer까지 실습합니다. 먼저 이 장에서는 PyTorch가 무엇인지?, 설치 방법, 기본적인 Pytorch 조작에 대해서 살펴보겠습니다.

---

**Contents**
1. [Import Pakage](#scrollTo=ufGZae8RBD4E)
2. [Pytorch Install](#scrollTo=pvEJXsaA6bta)
3. [Tensor Manipulation](#scrollTo=a3vgmiGogBH3)

**Reference**
- [PyTorch Tutorial](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html)
- [Deep Learning Zero To All:Pytorch](https://deeplearningzerotoall.github.io/season2/lec_pytorch.html)
<div align="left">
    <a href="https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html">
        <img src="https://drive.google.com/uc?id=1SwxpnRc2AHWFh4VcRZR6cYjRSRf20I2i" width="20%" alt=""/></a>
    <a href="https://github.com/deeplearningzerotoall/PyTorch">
        <img src="https://drive.google.com/uc?id=1mlhUOsH5NkieuGhynekXoxmiGa9J64pQ" width="17%" alt=""/></a>
</div>



## 1. What is Pytorch

Pytorch는 Python을 위한 오픈소스 머신러닝 라이브러리로 Torch를 기반으로 하는 최적화된 Deep Learning 텐서 라이브러리로 주로 GPU와 CPU를 사용하는 애플리케이션에 사용된다. PyTorch의 장점으로는 설치가 간편하며 이해와 디버깅이 쉬운 직관적이고 간결한 코드로 구성되어있고 파이썬 라이브러리(Numpy, Scipy, Cython)와 높은 호환성을 가진다. 또한 자동 미분 라이브러리를 이용하여 신경망 구현에 용이함을 가진다.



**파이토치의 구성** 

|  패키지 |   기술  |
|   ---   |   ---   |
|  torch  |강력한 GPU 지원 기능을 갖춘 메인 네임스페이스로 텐서 등의 다양한 수학함수가 포함되어 있으며 Numpy와 같은 구조를 가지고 있다.|
|torch.autograd|자동 미분을 위한 함수가 포함되어 있으며 자동 미분을 제어하는 기능과 자체 미분 가능 함수를 정의할때 사용하는 기반 클래스인 Function등이 포함되어 있다.|
|torch.nn|신경망을 구축하기 위한 다양한 데이터 구조나 레이어 등이 정의되어 있다.|
|torch.optim|SGD, RMSProp, Adam 등과 같은 최적화 알고리즘이 구현되어 있다.|
|torch.utils|쌕torch.nn|신경망을 구축하기 위한 다양한 데이터 구조나 레이어 등이 정의되어 있다.|
|torch.optim|SGD, RMSProp, Adam 등과 같은 최적화 알고리즘이 구현되어 있다.|
|torch.utils|Dataset, DataLoader 및 기타 유틸리티 기능이 구현되어 있다.|








## 2 Pytorch Install
본 실습에서는 Colab을 이용하여 실습을 진행하기 때문에 PyTorch를 따로 Install하지 않아도 되지만 어떻게 설치해야하는지에 대해서 간략히 살펴보려한다.


### 1) https://pytorch.org/ 에 접속한다.

[<img src='https://drive.google.com/uc?id=1isI2Q3x24RjFcsCOJx01xrqecHFsRqKF' width='800' height='400'>](https://pytorch.org/)

### 2) [Get Started](https://pytorch.org/get-started/locally/)에 들어간다.
- 자신의 환경에 알맞게 선택
- Run this Command를 복사해서 실행

[<img src='https://drive.google.com/uc?id=1C2W6WBAFlTeyjlK1dkC-h-mHFeY993Jz' width='800' height='400'>](https://pytorch.org/get-started/locally/)

## 3. Tensor Manipulation
텐서(tensor)는 배열(array)이나 행렬(matrix)과 매우 유사한 특수한 자료구조로 PyTorch에서는 텐서를 사용하여 모델의 입력(input)과 출력(output), 그리고 모델의 매개변수들을 부호화(encode)한다.

텐서는 GPU나 다른 하드웨어 가속기에서 실행할수 있다는 점만 제외하면 NumPy의 ndarray와 유사하며 실제로 텐서와 NumPy 배열(array)은 종동 동일한 내부(underly) 메모리를 공유할 수 있다. 또한 텐서는 자동미분(autograd)에 최적화 되어 있어 NumPy의 ndarray에 익숙하면 바로 Tensor를 사용할 수 있다.

### 3.1 Vector, Matrix and Tensor

---

<img align='right' src='https://drive.google.com/uc?id=1HMGXIhE0Zr6Q6UpLPhSA683yNCYxZ2dn' width='500' height='250'> 
- 2D Tensor(Typical Simple Setting)
    - batch size, dim
- 3D Tensor(Typical Computer Vision)
    - batch size, width, height
- 4D Tensor (Typical Computer vision)
    - batch size, channel, width, height


### 3.2 PyTorch Tensor

---




In [ ]:
import torch

**1D Array with PyTorch**

In [ ]:
t = torch.arange(7)
t = t.to(torch.float32)
x = torch.Tensor([0, 1, 2, 3, 4, 5, 6])
print(t)
print(x == t)

print("Rank  of tensor: ", t.ndim)
print("Shape of tensor: ", t.size()) # t.shape
print("tensor[0]   tensor[1] tensor[-1] = ", t[0], t[1], t[-1]) # Element
print("tensor[2:5] tensor[4:-1]         = ", t[2:5], t[4:-1])   # Slicing
print("tensor[:2]  tensor[3:]           = ", t[:2], t[3:])      # Slicing  

tensor([0., 1., 2., 3., 4., 5., 6.])
tensor([True, True, True, True, True, True, True])
Rank  of tensor:  1
Shape of tensor:  torch.Size([7])
tensor[0]   tensor[1] tensor[-1] =  tensor(0.) tensor(1.) tensor(6.)
tensor[2:5] tensor[4:-1]         =  tensor([2., 3., 4.]) tensor([4., 5.])
tensor[:2]  tensor[3:]           =  tensor([0., 1.]) tensor([3., 4., 5., 6.])


**2D Array with PyTorch**

In [ ]:
t = torch.arange(1,13).view(4,3) # torch.arange(1,13).reshape(4,3)
t = t.to(torch.float32)
x = torch.Tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]])
print(t)
print(x == t)
print("Rank  of tensor: ", t.ndim)
print("Shape of tensor: ", t.size())
print("tensor[0][0] tensor[2][1] tensor[3][2] = ", t[0][0], t[2][1], t[3][2]) # Element
print("tensor[0], tensor[:,0], tensor[0,:]    = ", t[0], t[:,0], t[0,:])      # Slicing
print("Shape of tensor[:, 1]", t[:, 1].size())
print("tensor[1:3,1:2] = \n", t[2:4,1:3]) # Slicing

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])
Rank  of tensor:  2
Shape of tensor:  torch.Size([4, 3])
tensor[0][0] tensor[2][1] tensor[3][2] =  tensor(1.) tensor(8.) tensor(12.)
tensor[0], tensor[:,0], tensor[0,:]    =  tensor([1., 2., 3.]) tensor([ 1.,  4.,  7., 10.]) tensor([1., 2., 3.])
Shape of tensor[:, 1] torch.Size([4])
tensor[1:3,1:2] = 
 tensor([[ 8.,  9.],
        [11., 12.]])


**데이터나 numpy array를 Tensor로 변환**

In [ ]:
# Directly from data
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(data)
print(x_data)

[[1, 2], [3, 4]]
tensor([[1, 2],
        [3, 4]])


In [ ]:
# From a Numpy array
np_data = np.array(data)
x_np = torch.from_numpy(np_data)
print(np_data)
print(x_np)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


In [ ]:
# Compare 2D NumPy array with 2D Torch tensor
t_2 = torch.from_numpy(arr_2)
print(t == t_2)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])


**Broadcasting**

In [ ]:
# Same shape
m1 = torch.Tensor([[3, 3]])
m2 = torch.Tensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [ ]:
# Vector + scalar
m1 = torch.Tensor([[1, 2]])
m2 = torch.Tensor([3]) # 3 -> [[3,3]]
print(m1 + m2)

tensor([[4., 5.]])


In [ ]:
# 2x1 vector + 1x2 vector
m1 = torch.Tensor([[1, 2]])
m2 = torch.Tensor([[3],[4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


**Multiplication VS Matrix Multiplication**

In [ ]:
space = 40
m1 = torch.Tensor([[1, 2], [3, 4]])
m2 = torch.Tensor([[1], [2]])
print("Shape of Matrix 1: ", m1.size()) # 2x2
print("Shape of Matrix 2: ", m2.size()) # 2x1
print(f"{'='* space}\nMultiplication Result(m1.matmul(m2)):\n{m1.matmul(m2)}\n{'='* space}") # 2x1
print(f"Matrix Multiplication Result(m1.mul(m2)):\n{m1.mul(m2)}\n{'='* space}") # 2x2

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
Multiplication Result(m1.matmul(m2)):
tensor([[ 5.],
        [11.]])
Matrix Multiplication Result(m1.mul(m2)):
tensor([[1., 2.],
        [6., 8.]])


**Mean**

In [ ]:
t = torch.Tensor([1, 2])
print(t.mean())
print(t.dtype)

tensor(1.5000)
torch.float32


In [ ]:
# Can't use mean() on integers
t = torch.LongTensor([1, 2])
print(t.dtype)
try:
    print(t.mean())
except Exception as exc:
    print(exc)

torch.int64
mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


In [ ]:
t = torch.Tensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


**Sum**

In [ ]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


**Max and Argmax**

In [ ]:
print(t.max()) # Returns one value: max

tensor(4.)


In [ ]:
print(t.max(dim=0)) # Returns two values: max and argmax
print("Max: ", t.max(dim=0)[0])
print("Argmax: ", t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [ ]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


**View(Reshape)**

In [ ]:
# from numpy
arr = np.arange(12).reshape(2,2,-1)
print(arr)
t = torch.Tensor(arr)
print(t)
print(t.size())

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])


In [ ]:
print(t.view(-1, 3))
print(t.view(-1, 3).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


**Squeeze**

In [ ]:
t = torch.Tensor(np.arange(3).reshape(3,1))
print(t)
print(t.size())

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [ ]:
print(t.squeeze())
print(t.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


## Unsqueeze

In [ ]:
t = torch.Tensor([0, 1, 2])
print(t)
print(t.shape)

tensor([0., 1., 2.])
torch.Size([3])


In [ ]:
print(t.unsqueeze(0))
print(t.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [ ]:
print(t.view(1, -1))
print(t.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [ ]:
print(t.unsqueeze(1))
print(t.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [ ]:
print(t.unsqueeze(-1))
print(t.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## Type Casting

In [ ]:
t = torch.LongTensor([1, 2, 3, 4])
print(t)
print(t.dtype)
print(t.float())

tensor([1, 2, 3, 4])
torch.int64
tensor([1., 2., 3., 4.])


In [ ]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [ ]:
print(bt.long(), bt.long().dtype)
print(bt.float(), bt.float().dtype)

tensor([1, 0, 0, 1]) torch.int64
tensor([1., 0., 0., 1.]) torch.float32


## Concatenate

In [ ]:
x = torch.Tensor([[1, 2], [3, 4]])
y = torch.Tensor([[5, 6], [7, 8]])
print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## Stacking

In [ ]:
x = torch.Tensor([1, 4])
y = torch.Tensor([2, 5])
z = torch.Tensor([3, 6])

In [ ]:
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [ ]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


## Ones and Zeros

In [ ]:
x = torch.Tensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [ ]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## In-place Operation

In [ ]:
x = torch.Tensor([[1, 2], [3, 4]])

In [ ]:
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
